### ISSUE TITLE
Feature request: output .fna file of reads (not) matching the database

### ISSUE THREAD

**Issue by colinbrislawn** [ncbi/magicblast#14]
Some aligners are able to output the query reads that do (or do not) match to the database.

`bbduk.sh outm=hits.fna out=misses.fna`
`vsearch --matched hits.fna --notmatched misses.fna`

I think this would be a convenient feature for magic-blast. ⚡️ 

Thanks for making a new splice-aware aligner!

**Comment by boratyng** [comment]
Thank you for using Magic-BLAST and for your suggestion. We plan to add this feature in a future release.

At this point we have ```-no_unaligned``` option, if you are only interested in reads that align to your target.

**Comment by y9c** [comment]
Hi @colinbrislawn,
There is a `-out_unaligned` argument for this in version 1.6.0 now.

**Comment by boratyng** [comment]
Additionally, you can use `-unaligned_fmt` option to select output format for unaligned reads. Choices are: SAM, tabular, and FASTA formats. The same format as for aligned reads is used by default.
