### ISSUE TITLE
request fo .gz inputs (fastq.gz especially)

### ISSUE THREAD

**Issue by FTouzain** [ncbi/magicblast#23]
Hello,
Thank you for the tool.
It might be nice to make magicblast accept in input fastq.gz files (both single-end or paired-end) because most of tools accept compressed reads and it avoid to uncompress specifically to this tool.
Thank you.
Best regards.

**Comment by boratyng** [comment]
Hi  @FTouzain,

Thank you for trying out Magic-BLAST. Magic-BLAST already reads gzipped FASTA and FASTQ files. We need to update documentation to include this fact. Please, try this for example
```
magicblast -query reads.fastq.gz -infmt fastq -db genome
```
No need for additional parameters. Magic-BLAST recognizes compressed files by the `.gz` extension, so the compressed file names must end with `.gz` and it works only for gzip compression. Please, let me know if it does not work for you.

Thanks,
Greg

**Comment by FTouzain** [comment]
Many thanks, I will try.
Best regards
Fabrice
