### ISSUE TITLE
magicblast against nt database

### ISSUE THREAD

**Issue by yeroslaviz** [ncbi/magicblast#24]
Hi,

I was wondering if it is possible to run the magicblast against the complete `nt` database?

I have downloaded the whole database and would like to run  a `fastq` files against it. Is it possible, or do I need to have only one specific file?

**Comment by boratyng** [comment]
Hi @yeroslaviz,

  Yes, you can run magicblast against complete `nt` database. Thank you for giving magicblast a try.
