### ISSUE TITLE
Splice alignment for prokaryotes genome

### ISSUE THREAD

**Issue by StephenLi55** [ncbi/magicblast#25]
Hi,

  I am trying to map some chimeric reads for my RNA-Seq data of Campylobacter. I am hoping the splice alignment of Magic-Blast can help. However, if I have understood the paper correctly, Magic-Blast splice alignment looks for the canonical splice sites, which are not present for prokaryotes. Is there anyway to map a chimeric reads to two separated genes without relying on the canonical splice site ?

  best wishes,

  Stephen

**Comment by boratyng** [comment]
Hi Stephen,

  Thank you for considering Magic-BLAST for your task. Yes, you will be able to align chimeric reads. Magic-BLAST uses splice signals to differentiate between an intron and a deletion. In the absence of splice signals you will get alignments with a long deletion between the genes. Please, be sure to use the latest version of Magic-BLAST: 1.5.0. The alignments with long deletions do not work as well in the earlier versions.

Thanks,
Greg
