### ISSUE TITLE
Write down read qual from the `fastq` input into the `sam` output file?

### ISSUE THREAD

**Issue by y9c** [ncbi/magicblast#32]
Seem that read quality field is missing in the sam output file.

**Comment by boratyng** [comment]
Magic-BLAST does not use read quality scores, because they are not always accurate. The scores are not included in the SAM report.

@yech1990, are quality scores needed in downstream analysis?

**Comment by y9c** [comment]
Hi @boratyng 

Yes. I know BLAST do not use quality score during the mapping step. But to make them output sam file **compatible** with other NGS tools, I think  Magic-BLAST can append the quality score back into the sam file after the mapping.

**Comment by boratyng** [comment]
Yes, we can do this, will try for the next release.

**Comment by boratyng** [comment]
Hi @y9c, Magic-BLAST 1.7.0 which was recently released reports read quality scores in the SAM output. Here are installation instructions: https://ncbi.github.io/magicblast/doc/download.html.
