### ISSUE TITLE
Update version in Bioconda

### ISSUE THREAD

**Issue by manu-script** [ncbi/magicblast#33]
Hi @boratyng,
Are there any build issues with the latest version of Magic-BLAST on Bioconda? If not, could you please push version 1.6.0 to Bioconda? 

Thank you,
Manu

**Comment by boratyng** [comment]
Hi Manu,

  I am working out problems with new features when run in docker and plan
to push the new version in early July.

Thanks,
Greg

**Comment by manu-script** [comment]
Great! Thanks a lot.

Cheers,
Manu

**Comment by boratyng** [comment]
Hi Manu,

  Just wanted to let you know that Magic-BLAST 1.6.0 is in Bioconda now. Sorry for the very long delay. There were more build issues that I initially anticipated.

Best,
Greg
