### ISSUE TITLE
magicblast can't parse the header of database

### ISSUE THREAD

**Issue by Rinoahu** [ncbi/magicblast#56]
hello, I used magicblast to map short reads to a fasta with >20000 reference sequences. I found that magicblast couldn't parse the header of the reference sequences. Instead, it turned the header into numbers. Is there any way to solve this?  thanks

**Comment by boratyng** [comment]
Hi @Rinoahu, I am sorry you ran into problems. I suspect that you created a BLAST database for your reference sequences and did not include the `-parse_seqids` flag. Please include it when running `makeblastdb`:
```
makeblastdb -in reference.fa -out reference -dbtype nucl -parse_seqids
```

If this does not help or you did not use `makeblastdb` before running `magicblast`, the please post your magicblast command line and an example of your reference sequence. Thanks.

**Comment by Rinoahu** [comment]
> Hi @Rinoahu, I am sorry you ran into problems. I suspect that you created a BLAST database for your reference sequences and did not include the `-parse_seqids` flag. Please include it when running `makeblastdb`:
> 
> ```
> makeblastdb -in reference.fa -out reference -dbtype nucl -parse_seqids
> ```
> 
> If this does not help or you did not use `makeblastdb` before running `magicblast`, the please post your magicblast command line and an example of your reference sequence. Thanks.

Works. Thank you!
