### ISSUE TITLE
missing scaffold names on sam header

### ISSUE THREAD

**Issue by cst-rmrz** [ncbi/magicblast#57]
The scaffold names should look something like this:
@HD	VN:1.0	SO:unsorted
@SQ	SN:Scaffold_1__2_contigs__length_78070536	LN:78070537
@SQ	SN:Scaffold_2__1_contigs__length_61731525	LN:61731525
@SQ	SN:Scaffold_3__3_contigs__length_114446166	LN:114446168
@SQ	SN:Scaffold_4__2_contigs__length_60228994	LN:60228995
@SQ	SN:Scaffold_5__2_contigs__length_88504823	LN:88504823
@SQ	SN:Scaffold_6__2_contigs__length_83591330	LN:83591330
@SQ	SN:Scaffold_7__2_contigs__length_80977755	LN:80977755
@SQ	SN:Scaffold_8__2_contigs__length_76899493	LN:76899493
@SQ	SN:Scaffold_9__1_contigs__length_70652527	LN:70652528

But `magicblast` formats them like this:
@HD	VN:1.0	GO:query
@SQ	SN:0	LN:78070537
@SQ	SN:1	LN:61731525
@SQ	SN:2	LN:114446168
@SQ	SN:3	LN:60228995
@SQ	SN:4	LN:88504823
@SQ	SN:5	LN:83591330
@SQ	SN:6	LN:80977755
@SQ	SN:7	LN:76899493
@SQ	SN:8	LN:70652528

With the changed scaffold names, the downstream analyses are really impossible for my pipeline. Is there a setting I'm not realizing to get `magicblast` to report the original scaffold names in the header of the SAM file?

**Comment by boratyng** [comment]
Hi @cst-rmrz, when you create a BLAST database for your target with `makeblastdb` you need to add `-parse_seqids` flag,, for example:
```
makeblastdb -in myseqs.fa -out mydb -dbtype nucl -parse_seqids
```

**Comment by cst-rmrz** [comment]
That was exactly the problem. 
I thought this was a bug, but I guess I just didn't know how to make a blast database ¯\_(ツ)_/¯
