### ISSUE TITLE
Error to install requirements.txt

### ISSUE THREAD

**Issue by Completex** [ncbi/magicblast#58]
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by boratyng** [comment]
Hi @Completex, could you provide more context? What is the command line that you are trying to run? Magic-BLAST binary does not require python or pip. Is this working for you?:
```
magicblast -version
```

**Comment by boratyng** [comment]
I am closing this issue, because there was no response. Please, reopen if you still have problems.
